### ISSUE TITLE
Weird slice_logic test output

### ISSUE THREAD

**Issue by SuperStacie** [thunlp/LLaVA-UHD#2]
Hi, thanks for the great work!
I just quickly tested your LLaVA-UHD.jpg using your slice_logic.py, is this supposed to be the right output?
<img width="847" alt="Screen Shot 2024-03-19 at 10 48 54 AM" src="https://github.com/thunlp/LLaVA-UHD/assets/42395418/ee46873c-7d19-4e7e-a4e3-aab3df6d2a2d">

**Comment by xrorrim** [comment]
yeah, this is correct. because our model is supposed to take any aspect-ratio image, this weird partern is for batch making.
