### ISSUE TITLE
How do you train your ViTs?

### ISSUE THREAD

**Issue by baichuanzhou** [thunlp/LLaVA-UHD#4]
Nice work on LLaVA-UHD!

Quick question:
1. How do you guys train the ViTs? I noticed [here](https://github.com/thunlp/LLaVA-UHD/blob/main/llava_uhd/train/llava-uhd/adapt_clip.py#L257) the decorator still exists.

**Comment by guozonghao96** [comment]
Thanks for paying attention to our work. We do not train the ViTs.

**Comment by baichuanzhou** [comment]
Ok, thanks!

**Comment by SuperStacie** [comment]
> Thanks for paying attention to our work. We do not train the ViTs.

Hi, thanks for the clarification, but I noticed you mentioned during fine-tuning stage, the ViT is fine-tuned "In our experiments, we show that ViT and position
embedding parameters can be kept frozen during pretraining, and updating these parameters during
the instruction-tuning stage is sufficient for good performance". Do you mean ViT is kept frozen all the time?
