### ISSUE TITLE
About the slice_logic

### ISSUE THREAD

**Issue by power0341** [thunlp/LLaVA-UHD#7]
the result of slicing looks very weird (haven't read the paper, may completely wrong 🙄)
OG:
![9cd8aab1f2ddbf6f15867247d4331016](https://github.com/thunlp/LLaVA-UHD/assets/2802813/6dd85ce9-28e8-437f-9906-f9b430838025)

then the 7 patches:
![image0](https://github.com/thunlp/LLaVA-UHD/assets/2802813/4b2e8f1c-4c0f-41ca-a3f0-70203532b23a)
![image1](https://github.com/thunlp/LLaVA-UHD/assets/2802813/7508e11a-f7b3-4f2e-867a-2d1f1e52175a)
![image2](https://github.com/thunlp/LLaVA-UHD/assets/2802813/4ddee6ca-22c4-4b15-949e-85446bb68089)
![image3](https://github.com/thunlp/LLaVA-UHD/assets/2802813/fe0cfa58-496f-47fb-bf03-79813bbb78c0)
![image4](https://github.com/thunlp/LLaVA-UHD/assets/2802813/ae22ea49-d2d8-4e52-9f6e-8ea2fd9b5a98)
![image5](https://github.com/thunlp/LLaVA-UHD/assets/2802813/cfd87a6c-50bc-49c6-8950-e10469361f40)
![image6](https://github.com/thunlp/LLaVA-UHD/assets/2802813/f70cfab0-a4bb-4c85-b1ea-603a11dc61e6)

**Comment by yfzhang114** [comment]
so what it the reason?

**Comment by power0341** [comment]
@yfzhang114 https://github.com/thunlp/LLaVA-UHD/blob/69e75d0cc6bc4d6000045f08f94852d2d465cd91/llava_uhd/train/llava-uhd/adapt_clip.py#L272
